services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: blogs-webapi:latest
    container_name: blogs-webapi
    ports:
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8083
      - ConnectionStrings__Default=Server=mysql;Port=3306;Database=blogsdb;User=root;Password=Zlj@123;SslMode=Preferred;
      - Redis__Host=redis
      - Redis__Port=6379
      - Redis__InstanceName=blogs_cache
      - Redis__Password= 
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    networks:
      - app-network
  # ========== 前端 Admin 管理后台 ==========
  admin-frontend:
    build:
      context: ./6_WebSite/Blogs.Admin
      dockerfile: Dockerfile
    image: blogs-admin:latest
    container_name: blogs-admin
    ports:
      - "8085:80"
    depends_on:
      - webapi
    restart: unless-stopped
    networks:
      - app-network

  # ========== 前端 Website 用户站点 ==========
  website-frontend:
    build:
      context: ./6_WebSite/Blogs.WebSite
      dockerfile: Dockerfile
    image: blogs-website:latest
    container_name: blogs-website
    ports:
      - "8086:80"
    depends_on:
      - webapi
    restart: unless-stopped
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: blogs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Zlj@123
      MYSQL_DATABASE: blogsdb
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: blogs-redis
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
      - "6377:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql-data:
  redis-data:

networks:
  app-network:
    external: true  